order_sys/urls.py
from django.contrib import admin
from django.urls import path, re_path
from web.views import account, level, customer, policy, my_order, my_transaction

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('login/', account.login, name="login"),
    path('email/login/', account.email_login, name="email_login"),
    path('email/send/', account.email_send, name="email_send"),
    path('logout/', account.logout, name="logout"),

    path('home/', account.home, name="home"),

    path('level/list/', level.level_list, name="level_list"),
    path('level/add/', level.level_add, name="level_add"),
    path('level/edit/<int:pk>/', level.level_edit, name="level_edit"),
    path('level/delete/<int:pk>/', level.level_delete, name="level_delete"),

    path('customer/list/', customer.customer_list, name="customer_list"),
    path('customer/add/', customer.customer_add, name="customer_add"),
    path('customer/edit/<int:pk>/', customer.customer_edit, name="customer_edit"),
    # 统一固定参数位置，在最后
    path('customer/reset/<int:pk>/', customer.customer_reset, name="customer_reset"),
    path('customer/delete/', customer.customer_delete, name="customer_delete"),
    # 交易记录
    path('customer/charge/<int:pk>/', customer.customer_charge, name="customer_charge"),
    path('customer/charge/<int:pk>/add/', customer.customer_charge_add, name="customer_charge_add"),

    # 　价格策略
    path('policy/list/', policy.policy_list, name="policy_list"),
    path('policy/add/', policy.policy_add, name="policy_add"),
    path('policy/edit/<int:pk>', policy.policy_edit, name="policy_edit"),
    path('policy/delete/', policy.policy_delete, name="policy_delete"),
    # 带正则表达式的路径,这个表示带一个数字
    re_path(r'policy/(\d+)', policy.policy_delete, name='xxx'),

    # 客户下单
    path('my/order/list/', my_order.my_order_list, name="my_order_list"),
    path('my/order/list/add/', my_order.my_order_list_add, name="my_order_list_add"),
    path('my/order/list/cancel/<int:pk>/', my_order.my_order_list_cancel, name="my_order_list_cancel"),
    # 客户交易记录
    path('my/transaction/list/', my_transaction.my_transaction_list, name="my_transaction_list"),
]

web/models.py
from django.db import models
import datetime


# Create your models here.

# 字段继承
class ActiveBaseModel(models.Model):
    '''
    这张表不生成，是基类
    '''
    # 逻辑删除
    active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "已删除")))

    class Meta:
        # 不建立表结构
        abstract = True


class Administrator(ActiveBaseModel):
    """管理员表"""
    # db_index创建索引
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    email = models.CharField(verbose_name="邮箱", max_length=44, db_index=True)
    # 两个字段功能不同，auto_now字段设置为True则创建或更新时时期会改变，auto_now_add则只保存创建日期，两个字段都可以加
    creat_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)

    # 设置管理员状态，这是逻辑上的删除，不是物理上的删除
    # 1 激活
    # 0 已删除
    # 使用choice，条件显示
    # active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "已删除")))

    def __str__(self):
        return self.username


# # 查询使用,返回属于行数据对象
# data = Administrator.objects.all()
# # 循环拿到每一行
# for item in data:
#     item.username
#     ...
#     # 显示对应的值
#     item.get_active_display()


# 客户等级表
class level(ActiveBaseModel):
    """客户等级表"""
    title = models.CharField(verbose_name="标题", max_length=32)
    percent = models.IntegerField(
        verbose_name="折扣",
        help_text="（请输入0-100的整数表示百分比。例如：90表示90%）",

    )

    # # 逻辑删除
    # active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "已删除")))

    # 调用对象，返回字段
    def __str__(self):
        return f'{self.title}({self.percent})'


# 客户表
class Customer(ActiveBaseModel):
    """客户表，管理员和用户表字段相同可以放在相同的表"""
    # db_index创建索引，
    # TODO:用户名和密码应该是联合唯一索引，用户名在前面，索引能命中查询用户名是否存在
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    email = models.CharField(verbose_name="邮箱", max_length=44, db_index=True)

    # 账户余额
    # max_digits ,允许最大位数；decimal_places 最小最大位数，小数点后2位 3
    balance = models.DecimalField(verbose_name="账户余额", default=0, max_digits=10, decimal_places=2)
    # # 客户等级
    # # 1. 如果就固定那几个级别不用更改
    # level_list = ((0, "vip"), (1, "svip"), (2, "ssvip"))
    # level = models.SmallIntegerField(verbose_name="状态", default=1, choices=level_list)
    # # 2. 如果需要随时改变，则需要重新创建客户等级表

    # 外键链接客户等级，通过verbose_name进行外键链接,to是链接的表名，on_delete是删除模式，models.CASCADE级联删除，等级没了数据也没了,limit_choices_to,自动筛选的条件,跨表找active为1的数据，如id__gt:2,id大于2
    # user_level = models.ForeignKey(verbose_name="折扣", to=level, on_delete=models.CASCADE, null=True, blank=True,limit_choices_to={'active': 1})
    user_level = models.ForeignKey(verbose_name="折扣", to=level, on_delete=models.CASCADE, null=True, blank=True)

    # # 逻辑删除
    # active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "已删除")))

    # 邀请制度，邀请人字段，就是外键绑定管理员
    creator = models.ForeignKey(verbose_name="创建者", to=Administrator, on_delete=models.CASCADE)
    # 创建日期
    creat_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True, null=True, blank=True)


# 价格策略表
class PriceTactics(models.Model):
    """价格策略，物理删除，多少数量有多少数量的价格
    1000 10
    2000 10

    """

    count = models.IntegerField(verbose_name="数量")
    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)


# 订单表
class Order(ActiveBaseModel):
    """订单表"""
    status_choice = (
        (1, "待执行"),
        (2, "正在执行"),
        (3, "已完成"),
        (4, "失败"),
        (5, "已撤单")
    )
    # 状态
    status = models.SmallIntegerField(verbose_name="订单状态", choices=status_choice, default=1)

    # 订单唯一标识，订单号
    cid = models.CharField(verbose_name="订单号", max_length=64, unique=True)
    url = models.URLField(verbose_name="视屏链接", db_index=True)

    # 下单数量
    count = models.IntegerField(verbose_name="数量")
    # # 不能进行全部关联，如果修改，之前的帐也会变
    # policy = models.ForeignKey(verbose_name="价格", to=PriceTactics,on_delete=)
    # 原价
    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)

    # 实际价格（会员等级打折）
    real_price = models.DecimalField(verbose_name="实际价格", default=0, max_digits=10, decimal_places=2)

    # 关联客户
    order_customer = models.ForeignKey(verbose_name="客户", to=Customer, on_delete=models.CASCADE)
    # 创建时间
    creat_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    # 备注信息
    remark = models.TextField(verbose_name="备注", null=True, blank=True)

    # 原播放量
    old_view_count = models.CharField(verbose_name="原播放量", max_length=32, default=0)


# 交易记录表
class TransactionRecord(ActiveBaseModel):
    """交易记录"""
    # 设置bootstrap样式,用于按钮渲染
    charge_type_class_mapping = {
        1: "success",
        2: "danger",
        3: "default",
        4: "info",
        5: "primary"
    }

    charge_type_choice = ((1, "充值"), (2, "扣款"), (3, "创建订单"), (4, "删除订单"), (5, "撤单"))
    charge_type = models.SmallIntegerField(verbose_name="类型", choices=charge_type_choice)

    # 客户
    trade_customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    # 充值
    amount = models.DecimalField(verbose_name="金额", default=0, max_digits=10, decimal_places=2)
    # 管路员,可为空（主要针对充值，扣款），有些操作不需要管理员
    creator = models.ForeignKey(verbose_name="管理员", to="Administrator", on_delete=models.CASCADE, null=True, blank=True)
    # 操作的订单，针对创建订单，删除订单，撤单，记录订单号，通过订单号来查找订单信息
    # order = models.ForeignKey(verbose_name="订单号", to="Order", on_delete=models.CASCADE, null=True, blank=True)
    # 需要通过订单号索引
    order_cid = models.CharField(verbose_name="订单号", max_length=64, null=True, blank=True, db_index=True)
    # 备注信息
    remark = models.TextField(verbose_name="备注", null=True, blank=True)

    # 创建日期
    creat_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True, null=True, blank=True)

web/forms/account.py
import random
from django import forms
# 字段进行正则表达式校验
from django.core.exceptions import ValidationError
from django_redis import get_redis_connection
from django.core.validators import RegexValidator

from web import models
from utils.encrypt import md5
from utils.send_email import send_email


# 定义一个类

class LoginForm(forms.Form):
    # 要校验的数据
    role = forms.ChoiceField(
        # 这个字段必须要有，不能为空
        # required=True,  # 不为空时改为False就行
        label="角色",
        choices=(("1", "管理员"), ("2", "客户")),
        # 可写正则表达式
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "id": "role",
                "name": "role"
            }
        ))

    # 调用form的模板生成html
    username = forms.CharField(
        # 这个字段必须要有，不能为空
        # required=True,
        label="用户名",
        widget=forms.TextInput(
            attrs={"class": "form-control",
                   "placeholder": "输入用户名",
                   "id": "username",
                   "name": "username"
                   }
        ))
    password = forms.CharField(
        # 这个字段必须要有，不能为空
        # 内部默认就不能为空
        # required=True,
        # label字段，能。出来
        label="密码",
        validators=[RegexValidator(r'^[0-9]+$', '密码必须是数字')],
        widget=forms.PasswordInput(
            attrs={"class": "form-control",
                   "placeholder": "输入密码",
                   "id": "password",
                   "name": "password"
                   }
        )
    )

    # 内部执行，抛出异常或返回原来的值
    def clean_username(self):
        # 获取上一次的返回值
        user = self.cleaned_data["username"]
        # 校验规则
        # 校验失败
        if len(user) < 3:
            # 抛出异常
            from django.core.exceptions import ValidationError
            raise ValidationError("用户名过短（小于三位）")
        # 返会重新赋值给self.cleaned_data["username"]
        return user

    # 对所有值进行校验，不能轻易返回值，下次使用时会用这次返回的值
    # 无论前面的校验是否执行都会执行，使用取的self.cleaned_data不一定对

    def clean_password(self):
        password = md5(self.cleaned_data["password"])
        return password


# 生成标签，提交表单之后的校验，走中间件
class EmailLoginForm(forms.Form):
    role = forms.ChoiceField(
        # 这个字段必须要有，不能为空
        # required=True,  # 不为空时改为False就行
        # label="角色",
        choices=(("1", "管理员"), ("2", "客户")),
        # 可写正则表达式
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "name": "role"
            }
        ))

    # 调用form的模板生成html
    email = forms.CharField(
        # 这个字段必须要有，不能为空
        # required=True,
        # label="邮箱",
        validators=[RegexValidator(r"^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$", '邮箱格式错误')],
        widget=forms.TextInput(
            # 不需要写lable的原因是页面上用的是固定的写法，没有用循环生成

            attrs={"class": "form-control",
                   "placeholder": "输入邮箱",
                   "name": "email"
                   },
        ))

    code = forms.CharField(
        # 这个字段必须要有，不能为空
        # 内部默认就不能为空
        # required=True,
        # label字段，能。出来
        # label="邮箱验证码",
        validators=[RegexValidator(r'^[0-9]{4}$', '验证码是数字')],
        widget=forms.TextInput(
            attrs={"class": "form-control",
                   "placeholder": "输入验证码",
                   "name": "code"
                   }
        )
    )

    # 验证过程写在code钩子里面，能拿到email
    def clean_code(self):
        # 邮箱验证,用户提交的数据
        # 邮箱如果上一个字段校验不通过就获取不到，所以要用get去拿
        email = self.cleaned_data.get("email")
        code = self.cleaned_data["code"]
        if not code:
            # 返回空后校验并不会通过，应该是返回真正的code
            return code

        # 拿去缓存的数据，进行校验
        conn = get_redis_connection("default")
        cache_code = conn.get(email)

        # 缓存不存在
        if not cache_code:
            raise ValidationError("验证码无效")

        # redis拿出来是字节
        if code != cache_code.decode("utf-8"):
            raise ValidationError("验证失败")
        # 正常返回
        return code


# 专门为校验邮箱写的字段
class EmailForm(forms.Form):
    role = forms.ChoiceField(
        # 这个字段必须要有，不能为空
        # required=True,  # 不为空时改为False就行
        # label="角色",
        choices=(("1", "管理员"), ("2", "客户")),
        # 可写正则表达式
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "name": "role"
            }
        ))

    email = forms.CharField(
        label="邮箱地址",
        required=True,
        validators=[RegexValidator(r"^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$", '邮箱格式错误')])

    # 写email的钩子方法时，能调用到role，因为role字段写在email前面，有先后顺序的
    # 如果前面校验不通过，就拿不到前面的值

    def clean_email(self):

        # 如果没有获取到前面的值，就是前面的值校验失败，直接返回
        role_ = self.cleaned_data["role"]
        email_ = self.cleaned_data["email"]
        if not role_:
            return email_

        # 前面校验成功就去数据库查有没有
        if role_ == "1":
            # 进入管理员表查询，需要查询状态是否唯一
            exist = models.Administrator.objects.filter(active=1, email=email_).exists()
            # print(1)
        else:
            exist = models.Customer.objects.filter(active=1, email=email_).first()

        if not exist:
            # 抛出异常
            raise ValidationError("邮箱不存在")

        code = random.randint(1000, 9999)
        is_send = send_email(email_, code)

        if not is_send[0]:
            raise ValidationError(is_send[1])

        conn = get_redis_connection("default")
        # 设置值和验证码,ex超时时间60s
        conn.set(email_, code, ex=120)
        return email_

web/templates/customer_charge.html
{% extends 'layout.html' %}
{% load static %}
{% load permission %}
{% load color %}

{% block css %}
    <style>
        .error_massage {
            position: absolute;
            top: 32px;
        }
    </style>
{% endblock %}

{% block content %}
    <!--表格-->
    <table class="table table-bordered">
        <caption>客户列表</caption>

        <div style="margin-bottom: 5px" class="clearfix">
            <button class="btn btn-success" id="btnAdd">
                新建
            </button>
        </div>


        <thead>
        <tr>
            <th>ID</th>
            <th>类型</th>
            <th>金额</th>
            <th>订单号</th>
            <th>创建时间</th>
            <th>其他</th>

        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <!--自定义属性，用于定位行-->
            <tr row-id="{{ row.id }}">
                <!--获取select选项的方法-->
                <td>{{ row.id }}</td>
                <td>
                    <span class="btn btn-{{ row.charge_type|color }}">{{ row.get_charge_type_display }}</span>
                </td>
                <td>{{ row.amount }}</td>
                <td>
                    {% if row.order_cid %}
                        {{ row.order_cid }}
                    {% else %}
                        -
                    {% endif %}

                </td>
                <td>{{ row.creat_date|date:'Y-m-d H:i:s' }}</td>
                <td>
                    {% if row.remark %}
                        {{ row.remark }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <!--方案2直接跨表找-->
                {#                <td>{{ row.creator.username}}</td>#}
            </tr>
        {% endfor %}


        </tbody>
    </table>

    <ul class="pagination">
        <!--把字符串变成标签-->
        {{ pager.html }}
    </ul>

    <!-- 模态框（Modal） -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true" style="color: red">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--展示的内容-->
                <!--标题-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">新建数据</h4>
                </div>
                <!--内容-->
                <div class="modal-body">


                    <form class="form-horizontal" role="form" id="addForm">
                        {% csrf_token %}
                        {% for field in form %}

                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">类型</label>
                                <div class="col-sm-10" style="position: relative">
                                    {{ field }}
                                    <span style="color: red" class="error_massage">{{ field.errors.0 }}</span>
                                </div>
                            </div>

                        {% endfor %}


                    </form>


                </div>

                <!--关闭和确定-->
                <div class="modal-footer">
                    <!--这两个字段可以控制对话框的消失与显现data-dismiss="modal"，data-toggle="modal"-->
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="btnAddSubmit" style="position: relative">提交
                        <span style="color: red;position: absolute;top: 30px;left: 10px" class="deleteError"></span>
                    </button>
                    <!--展示错误信息-->

                </div>


            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>


{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#btnAdd').click(function () {
                $('#addModal').modal('show');
                //绑定事件
                $('#btnAddSubmit').click(function () {
                    $.ajax({
                        url: '{% url "customer_charge_add" pk=pk %}',
                        type: 'POST',
                        //拿到form表单
                        data: $('#addForm').serialize(),
                        dataType: 'JSON',
                        success: function (res) {
                            if (res.status) {
                                //页面刷新
                                window.location.reload();
                            } else {
                                $.each(res.detail, function (k, v) {
                                    $('#id_' + k).next().text(v);
                                })
                            }
                        }

                    })
                })
            })
        })
    </script>

{% endblock %}

web/templates/email_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--直接写路径-->
    <!--<link rel="stylesheet" href="/static/bootstrap-3.4.1/css/bootstrap.css">-->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <style>
        .box {
            width: 480px;
            border: 1px solid #dddddd;
            margin-left: auto;
            margin-right: auto;
            margin-top: 70px;
            padding: 10px 20px 10px 20px;
            box-shadow: 5px 5px 5px 5px;
        }

        .error_message {
            color: red;
            position: absolute
        }
    </style>


</head>
<body>
<div class="box">
    <h1 style="text-align: center">邮箱登入</h1>
    <!--novalidate去除表单上的默认非空验证-->
    <form method="post" id="email_form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_role">角色</label>
            {{ form.role }}
            <span class="error_message">{{ form.role.errors.0 }}</span>
        </div>

        <div class="form-group">
            <label for="id_email">邮箱</label>
            <div class="row">
                <div class="col-md-7">
                    {{ form.email }}
                </div>
                <div class="col-md-5">
                    <!--button默认type类型为submit-->
                    <button class="btn btn-success col-lg-4" id="send_btn" type="button">发送</button>
                </div>
            </div>
            <span class="error_message">{{ form.email.errors.0 }}</span>
        </div>

        <div class="form-group">
            <label for="id_code">验证码</label>
            {{ form.code }}
            <span class="error_message">{{ form.code.errors.0 }}</span>
        </div>
        <button type="button" class="btn btn-success" id="email_login">登入</button>
        <a id="2" href="{% url 'login' %}" style="float: right">密码登入</a>
    </form>
</div>

<script src={% static "js/jquery3.6.0.js" %}></script>
<script src={% static "js/csrf.js" %}></script>
<script>
    //页面框架加载完成自动执行，不是全部页面加载出来
    $(function () {
        //执行绑定
        bindSendEmailEvent();

        bindLoginEvent();
    })

    function bindLoginEvent() {
        //提交表单的请求事件（提交ajax请求）
        $("#email_login").click(function () {
            //清除所有错误信息
            console.log(1)
            $(".error_message").empty()
            console.log(2)
            $.ajax({
                url: "{% url 'email_login' %}",
                type: "POST",
                data: $("#email_form").serialize(),
                dataTypes: "JSON",
                success: function (res) {
                    console.log(res)
                    if (res.status) {
                        {#利用location.href进行从定向#}
                        location.href = res.data;
                    } else {
                        $.each(res.detail, function (k, v) {
                            if (k === "email") {
                                //邮箱的错误返回,相对定位不影响布局！！！
                                $("#id_" + k).parent().parent().next().text(v[0]);
                            } else {
                                //其他的错误返回
                                $("#id_" + k).next().text(v[0]);
                            }

                        })
                    }
                }
            })

        })
    }

    //绑定方法，邮箱校验，获取邮箱，发送请求
    function bindSendEmailEvent() {
        //发送邮箱的请求事件
        $("#send_btn").click(function () {
            //清除错误信息
            $(".error_message").empty()
            // 获取邮箱,向后台发送请求
            //1. 获取邮箱，向后台发送请求
            var email_ = $("#id_email").val();
            var role_ = $('#id_role').val();
            {#var Is_Email_ = IsEmail(email_);#}
            var Is_Email_ = 1;
            if (!Is_Email_) {
                console.log("邮箱不正确");
            } else {
                //判断邮箱是否合法
                var xhr = $.ajax({
                    //导入是不能这么用
                    url: "{% url 'email_send' %}",
                    //type:"GET",
                    //POST请求需要到游览器里面的cookie去拿csrftoken，添加进请求头里面，django读那个请求头就写进哪里
                    //调用django提供的函数获取
                    //要用ajax请求页面必须携带
                    type: 'POST',
                    headers: {
                        //可以不用带
                    },
                    data: {email: email_,role:role_},
                    {#把js字符串可能得对象转化为对象#}
                    dataTypes: "JSON",
                    success: function (res) {
                        //res是返回的对象
                        console.log(1, res.detail);
                        if (res.status) {
                            //校验成功后做的操作
                            console.log("成功")
                            ChangeSecond();
                            //判断是否校验成功
                        } else {
                            //校验失败后做的操作
                            //each循环对象，执行匿名函数
                            //{'status': False, 'detail': forms.errors}循环detail里面的字典，forms.errors
                            $.each(res.detail, function (k, v) {
                                console.log(2, k);
                                console.log(3, v);
                                //console.log(4,$("#id_" + k).parent().parent().next()[0]);
                                {#$("#id_" + k).next().next().text(v[0]);#}
                                //只针对邮箱的错误返回
                                $("#id_" + k).parent().parent().next().text(v[0]);

                            })
                        }

                    },
                })

            }
        })


    }


    //读秒效果
    function ChangeSecond() {
        //2. 点击事件变成读秒
        var $emailBtn = $("#send_btn");
        //找到标签，添加读秒内容，按钮值在val中
        {#console.log(1,$emailBtn.text());#}
        // 添加禁用属性
        $emailBtn.prop("disabled", true);
        // 定时器,一千毫秒执行一次
        var time = 59;
        var ID = setInterval(function () {
            $emailBtn.text(time + "秒");
            time = time - 1;
            if (time < 1) {
                clearInterval(ID);
                //去除禁用状态，可点击发送
                $emailBtn.text("发送");
                $emailBtn.prop("disabled", false);

            }
        }, 1000)

    }

    //邮箱校验
    function IsEmail(str) {
        var reg = /^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;
        return reg.test(str);
    }


</script>

</body>
</html>

web/templates/form(02).html
<!--继承模板-->
{% extends "layout.html" %}

{% block content %}
    <!--表单操作-->
    <form class="form-horizontal" role="form" method="post">
        <!--添加浮动会清除-->
        <div class="row clearfix">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-sm-6">
                    <div class="form-group" style="padding: 10px">
                        <label for="{{ field.id_for_label }}" class="control-label"
                               style="color: #9d9d9d">{{ field.label }}{{ field.help_text }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <span style="color: red">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div>
            <button type="submit" class="btn btn-success">保存</button>
        </div>
    </form>
{% endblock %}

web/templates/home.html
<!--继承模板-->
{% extends "layout.html" %}

{% block content %}
    <h3>欢迎登入</h3>
{% endblock %}

web/templates/my_order_list.html
<!--继承模板-->
{% extends "layout.html" %}
{% load static %}

{% block css %}
    <style>
        .top-message-error {
            position: fixed;
            left: 0;
            right: 0;
            width: 200px;
            margin-left: auto;
            margin-right: auto;
            height: 50px;
        }

    </style>


{% endblock %}

{% block content %}
    {% if messages %}
        <div class="top-message-error">

            {% for obj in messages %}
                <div class="alert alert-{{ obj.level_tag }}">
                    <ol>{{ obj.message }}</ol>
                </div>
            {% endfor %}

        </div>
    {% endif %}



    <!--表格-->
    <table class="table table-bordered">
        <caption>我的订单</caption>
        <div style="margin-bottom: 5px">
            <a class="btn btn-success" href="{% url 'my_order_list_add' %}"><i class="bi bi-apple"></i>新建</a>
        </div>
        <thead>
        <tr>
            <th>订单号</th>
            <th>视频地址</th>
            <th>数量</th>
            <th>价格</th>
            <th>原播放量</th>
            <th>创建时间</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr role-id="{{ row.id }}">
                <td>{{ row.cid }}</td>
                <td>{{ row.url }}</td>
                <td>
                    {{ row.count }}
                </td>
                <td>{{ row.real_price }}({{ row.price }})</td>
                <td>{{ row.old_view_count }}</td>
                <td>{{ row.creat_datetime }}</td>
                <td>{{ row.get_status_display }}</td>
                <td>
                    {% if row.status == 1 %}
                        <a href='{% url 'my_order_list_cancel' pk=row.id %}' class="btn btn-danger btn-xs">撤单</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul class="pagination">
        <!--把字符串变成标签-->
        {{ pager.html }}
    </ul>

{% endblock %}



{% block js %}
    <script>
        setTimeout(function () {
            $('.top-message-error').addClass('hide');
        }, 5000);
    </script>

{% endblock %}

web/templates/permission.html
{% extends 'layout.html' %}

{% block content %}
    <h3>无权访问</h3>
{% endblock %}